name: Germline Alignment and Variant Calling
description: Perform alignment and variant calling with BWA-MEM and DNAscope
stages:
  - name: Alignment with BWA-MEM
    description: Align FASTQ files with BWA-MEM
    task_path: bwa.task.yaml
    depends_on: []

    glob_parameter:
      label: FASTQ Base Folder
      path:
        type: directory
        supports_location_mode: 'read_only'
      glob_ex: '**/*_*.f*q.gz'
      output_parameters:
        - task_parameter_name: input_folder
          expression: '${file_directory}'
        - task_parameter_name: sample_name
          expression: '${2}'
      help: "The folder containing the FASTQ file(s) to align. \nThe number of samples (and therefore the number of runs) is determined by the number of files matching the glob expression. \nSee the glob expression help section for help with writing glob expressions to match your data."
      
    task_parameters:
      - name: output_folder 
        label: Output Folder
        type: directory
        supports_location_mode: 'no_append'
        help: "The output folder for alignment results. This folder will also be used for the output location for the variant-calling step. NOTE: This folder will *not* be used for the output VarSeq project, should the VSPipeline step be selected. Projecst are automatically output to AppData/Projects."

      - name: model_base_path
        label: Sentieon Models Base Path
        group: Advanced Options
        type: directory
        supports_location_mode: 'read_only'
        optional: true
        help: "Optionally specify the Sentieon models base path. If not provided, the default models base path will be used. Note that the default models base path must be downloaded and set appropriately. This is only if you select a machine learning model."

      - name: ml_model
        value: "None"
        label: Machine Learning Model
        type: enum
        choices: [None, Element Biosciences WGS 2.0, Illumina WES 2.1, Illumina WGS 2.2,
                  MGI WES 2.0, MGI WGS 2.0, Salus WES 1.0, Salus WGS 1.0, 
                  Ultima Genomics WGS 1.0]
        optional: false
        help: "The Sentieon machine learning model to use for improvements to speed and accuracy for alignment and variant-calling. Leave as None if your data does not match any of the available options. See Sentieon's GitHub page for more information."

      - name: ref_fasta
        label: Reference File (FASTA)
        type: file
        supports_location_mode: 'read_only'
        optional: true
        help: "Optionally specify the reference file to align to. If not provided, the default reference file will be used. Note that the default reference file must be downloaded and set appropriately."

      - name: use_prefix
        label: Use Sample Name as Prefix Filter
        type: stage
        stage_parameter_expression: "true"

  - name: Variant Calling with DNAscope 
    description: Variant calling from an alignment file with Sentieon's DNAscope algorithm
    task_path: dnascope.task.yaml
    depends_on:
      - Alignment with BWA-MEM
    
    glob_parameter:
      label: Alignment Folder
      path:
        type: stage
        stage: Alignment with BWA-MEM
        parameter: output_folder
      glob_ex: '**/*_*.bam'
      output_parameters:
        - task_parameter_name: input_file
          expression: '${0}'
        - task_parameter_name: sample_name
          expression: '${2}'

    task_parameters:
      - name: output_folder
        label: Output Folder
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${output_folder}"

      - name: model_base_path
        label: Sentieon Models Base Path
        group: Advanced Options
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${model_base_path}"

      - name: ml_model
        label: Machine Learning Model
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ml_model}"
        optional: false

      - name: ref_fasta
        label: Reference File (FASTA)
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ref_fasta}"

      - name: copy_fasta_to_workdir
        label: Copy Reference FASTA to Working Directory 
        type: boolean
        value: "false"
        help: "If enabled, the reference FASTA will be copied to the working directory before the variant-calling step. This is likely to yield better performance for larger input files."

  - name: Create VarSeq project
    description: Create a project with called variants
    run_step: optional_default_skip
    task_path: vspipeline.task.yaml
    depends_on:
      - Variant Calling with DNAscope

    task_parameters:
      - name: base_path
        label: Input Folder
        type: stage
        stage: Variant Calling with DNAscope
        stage_parameter_expression: "${output_folder}"

      - name: project_name
        label: Project Name
        type: string
        optional: true
        help: "The name of the VarSeq project to create. If not provided, the project name will be derived from the sample name derived from the glob expression."

      - name: project_template
        label: VarSeq Project Template
        type: file
        supports_location_mode: 'read_only'
        help: "The template to use for the VarSeq project."
        path: /AppData/VarSeq/User Data/ProjectTemplates/

      - name: overwrite_project
        label: Overwrite Existing VarSeq Projects
        type: boolean
        value: "true"
        help: "If enabled, existing VarSeq projects with the same name will be overwritten."