name: Germline Alignment and Variant Calling
description: Perform alignment and variant calling with BWA-MEM and DNAscope
stages:
  - name: Alignment with BWA-MEM
    description: Align FASTQ files with BWA-MEM
    task_path: bwa.task.yaml
    depends_on: []

    glob_parameter:
      label: FASTQ Base Folder
      path:
        type: directory
      glob_ex: '**/*_*.f*q.gz'
      output_parameters:
        - task_parameter_name: input_folder
          expression: '${file_directory}'
        - task_parameter_name: sample_name
          expression: '${2}'
      
    task_parameters:
      - name: output_folder 
        label: Output Folder
        type: directory

      - name: model_base_path
        label: Sentieon Models Base Path
        group: Advanced Options
        type: directory
        value: "CloudStorage/resources/sentieon_models"

      - name: ml_model
        value: "None"
        label: Machine Learning Model
        type: enum
        choices: [None, Element Biosciences WGS 2.0, Illumina WES 2.1, Illumina WGS 2.2,
                  MGI WES 2.0, MGI WGS 2.0, Salus WES 1.0, Salus WGS 1.0, 
                  Ultima Genomics WGS 1.0]
        optional: false

      - name: ref_fasta
        label: Reference File (FASTA)
        type: file
        value: "CloudStorage/resources/hg38_noalt/GCA_000001405.15_GRCh38_no_alt_analysis_set_maskedGRC_exclusions_v2.fasta"

      - name: use_prefix
        label: Use Sample Name as Prefix Filter
        type: stage
        stage_parameter_expression: "true"

  - name: Variant Calling with DNAscope 
    description: Variant calling from an alignment file with Sentieon's DNAscope algorithm
    task_path: dnascope.task.yaml
    depends_on:
      - Alignment with BWA-MEM
    
    glob_parameter:
      label: Alignment Folder
      path:
        type: stage
        stage: Alignment with BWA-MEM
        parameter: output_folder
      glob_ex: '**/*_*.bam'
      output_parameters:
        - task_parameter_name: input_file
          expression: '${0}'
        - task_parameter_name: sample_name
          expression: '${2}'

    task_parameters:
      - name: output_folder
        label: Output Folder
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${output_folder}"

      - name: model_base_path
        label: Sentieon Models Base Path
        group: Advanced Options
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${model_base_path}"

      - name: ml_model
        label: Machine Learning Model
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ml_model}"
        optional: false

      - name: ref_fasta
        label: Reference File (FASTA)
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ref_fasta}"

      - name: copy_fasta_to_workdir
        label: Copy Reference FASTA to Working Directory 
        type: boolean
        value: "false"
