name: Somatic Alignment and Variant Calling
description: Perform alignment and variant calling with BWA-MEM and TNscope
stages:
  - name: Alignment with BWA-MEM
    description: Align FASTQ files with BWA-MEM
    task_path: bwa.task.yaml
    depends_on: []

    glob_parameter:
      label: FASTQ Base Folder
      path:
        type: directory
      glob_ex: '**/*_*.f*q.gz'
      output_parameters:
        - task_parameter_name: input_folder
          expression: '${file_directory}'
        - task_parameter_name: sample_name
          expression: '${2}'
      
    task_parameters:
      - name: output_folder 
        label: Output Folder
        help: "The output folder for the resulting alignment files, VCFs, and (optional) metrics files."
        type: directory

      - name: ref_fasta
        label: Reference File (FASTA)
        type: file
        value: "CloudStorage/resources/hg38_noalt/GCA_000001405.15_GRCh38_no_alt_analysis_set_maskedGRC_exclusions_v2.fasta"

      - name: ml_model
        label: ML Model
        type: stage
        help: "The ML model to use for Sentieon's alignment and variant calling.\nOnly Ultima Genomics WGS is supported for somatic data."
        stage_parameter_expression: "None"
        value: "None"

      - name: use_prefix
        label: Use Sample Name as Prefix Filter
        type: stage
        stage_parameter_expression: "true"

      - name: perform_dedup
        label: Perform Deduplication (De-Select for Amplicon Data)
        type: boolean
        value: "true"

  - name: Generate Batch Parameter File
    description: Generate a batch parameter file for the alignment and variant calling workflow
    task_path: generate_batch_parameter_file.task.yaml
    depends_on:
      - Alignment with BWA-MEM
    
    task_parameters:
      - name: input_folder
        label: Input Folder
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: ${output_folder}
  
  - name: Variant Calling with TNscope
    description: Variant calling from an alignment file with Sentieon's DNAscope algorithm
    task_path: tnscope.task.yaml
    depends_on:
      - Generate Batch Parameter File
    
    glob_parameter:
      label: Alignment Folder
      path:
        type: stage
        stage: Alignment with BWA-MEM
        parameter: output_folder
      glob_ex: '*/*_*.bam'
      output_parameters:
        - task_parameter_name: input_file
          expression: '${0}'
        - task_parameter_name: sample_name
          expression: "${2}"

    task_parameters:
      - name: output_folder
        label: Output Folder
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${output_folder}"

      - name: ref_fasta
        label: Reference File (FASTA)
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ref_fasta}"
