name: Family Alignment and Variant Calling
description: Perform alignment and variant calling with BWA-MEM and DNAscope, and perform joint-calling for catalog-defined families
stages:
  - name: Alignment with BWA-MEM
    description: Align FASTQ files with BWA-MEM
    task_path: bwa.task.yaml
    depends_on: []

    glob_parameter:
      label: FASTQ Base Folder
      path:
        type: directory
        supports_location_mode: 'read_only'
      glob_ex: '**/*_*.f*q.gz'
      output_parameters:
        - task_parameter_name: input_folder
          expression: '${file_directory}'
        - task_parameter_name: sample_name
          expression: '${2}'
      help: "The folder containing the FASTQ file(s) to align. \nThe number of samples (and therefore the number of runs) is determined by the number of files matching the glob expression. \nSee the glob expression help section for help with writing glob expressions to match your data."
            
    task_parameters:
      - name: output_folder 
        label: Output Folder
        type: directory
        supports_location_mode: 'no_append'

      - name: model_base_path
        label: Sentieon Models Base Path
        group: Advanced Options
        type: directory
        supports_location_mode: 'read_only'
        optional: true

      - name: ml_model
        value: "None"
        label: Machine Learning Model
        type: enum
        choices: [None, Element Biosciences WGS 2.0, Illumina WES 2.1, Illumina WGS 2.2,
                  MGI WES 2.0, MGI WGS 2.0, Salus WES 1.0, Salus WGS 1.0, 
                  Ultima Genomics WGS 1.0]
        optional: false

      - name: ref_fasta
        label: Reference File (FASTA)
        type: file
        supports_location_mode: 'read_only'
        optional: true
        help: "Optionally specify the reference file to align to. If not provided, the default reference file will be used. Note that the default reference file must be downloaded and set appropriately."

      - name: use_prefix
        label: Use Sample Name as Prefix Filter
        type: stage
        stage_parameter_expression: "true"

  - name: Generate Batch Parameter File for Family Joint Calling
    description: Generate a batch parameter file of family relationships for joint calling
    task_path: generate_batch_parameter_file.task.yaml
    depends_on:
      - Alignment with BWA-MEM
    
    task_parameters:
      - name: input_folder
        label: Input Folder
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${output_folder}"

      - name: sample_type
        label: Sample Type
        type: stage
        stage: Generate Batch Parameter File for Family Joint Calling
        stage_parameter_expression: "Family"
        value: "Family"

  - name: Variant Calling with DNAscope 
    description: Variant calling from an alignment file with Sentieon's DNAscope algorithm
    task_path: dnascope.task.yaml
    depends_on:
      - Generate Batch Parameter File for Family Joint Calling
    
    batch_file_parameter:
      path: 
        base_path:
          type: stage
          stage: Alignment with BWA-MEM
          parameter: output_folder
        file: "family_batch_parameters.tsv"

    task_parameters:
      - name: output_folder
        label: Output Folder
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${output_folder}"

      - name: model_base_path
        label: Sentieon Models Base Path
        group: Advanced Options
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${model_base_path}"

      - name: ml_model
        label: Machine Learning Model
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ml_model}"
        optional: false

      - name: ref_fasta
        label: Reference File (FASTA)
        type: stage
        stage: Alignment with BWA-MEM
        stage_parameter_expression: "${ref_fasta}"

  - name: Create VarSeq project
    description: Create a project with called variants
    run_step: optional_default_skip
    task_path: vspipeline.task.yaml
    depends_on:
      - Variant Calling with DNAscope

    task_parameters:
      - name: base_path
        label: Input Folder
        type: stage
        stage: Variant Calling with DNAscope
        stage_parameter_expression: "${output_folder}"

      - name: project_name
        label: Project Name
        type: string
        optional: true
  
      - name: project_template
        label: VarSeq Project Template
        type: file
        supports_location_mode: 'read_only'
        optional: false
        help: "The template to use for the VarSeq project."
        path: /AppData/VarSeq/User Data/ProjectTemplates/

      - name: overwrite_project
        label: Overwrite Existing VarSeq Projects
        type: boolean
        value: "true"

